exclude: ".venv|tests/dev/|tests/fixtures/"
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
        args: [--remove]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        language: python
        types: [python]
        args: ["--select=E9,F63,F7,F82"]

  # - repo: https://github.com/python-jsonschema/check-jsonschema
  #   rev: 0.22.0
  #   hooks:
  #     - id: check-jsonschema
  #       additional_dependencies: ["pyjson5"]
  #       name: "Check QDT scenarii"
  #       files: ^qdt/[^/]+$
  #       types: [yaml]
  #       args:
  #         [
  #           "--schemafile",
  #           "https://raw.githubusercontent.com/Guts/qgis-deployment-cli/main/docs/schemas/scenario/schema.json",
  #         ]
